### ISSUE TITLE
De-Lisp the syntax

### ISSUE THREAD

**Issue by jwhitfieldseed** [jwhitfieldseed/peach#14]
Peach started out as a Lisp but I want to take it in a different direction: somehow it doesn't fit with static typing. Also, I want the language to feel natural to people with some JavaScript experience.

At first:
* [x] Add <strike>vector</strike> array syntax `[]` #15
* [x] Remove quoted expressions #15
* [x] DestructuredList -> Destructured<strike>Vector</strike>Array #15
* [x] List -> Call #15
* [x] Rename vector -> array
* [x] `?` -> Regular `if/else` construct
* [x] `==` for equality
* [x] `def`-> infix `Name = Expression`
* [x] Comment is `#` only

Bigger changes to make later:

* Infix operators #22 
* Paren-less function calls / parens for generic grouping #23
